### ISSUE TITLE
Line Chart bad performance with sideTitle

### ISSUE THREAD

**Issue by a43mrk** [imaNNeoFighT/fl_chart#357]
Hellow! I made and line chart with about 3 thousands point without sideTitles and i noticed that the performance is really different! without x sideTitle is fast but when enabling them my device is about to freeze :(

**Comment by igoriuz** [comment]
Could you please try out the current dev-branch?
Replace **fl_chart** in your pubspec.yaml and do `flutter pub upgrade`

```
dependencies:
  fl_chart:
    git: 
      url: https://github.com/imaNNeoFighT/fl_chart.git
      ref: dev      

```
